#!/usr/bin/env bash
echo "Cloning dependencies"
git clone https://github.com/Thagoo/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-17.0 gcc
git clone https://github.com/Thagoo/AnyKernel3 AnyKernel
echo "Done"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
TANGGAL=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER=Ryu
export KBUILD_BUILD_HOST=circle
git config --global user.email "marizky93@gmail.com"
git config --global user.name "ryu2374"
# sticker plox
function sticker() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendSticker" \
        -d sticker="CAACAgUAAx0CTxcDWAACAytejG8rgsUESQNeOxGqbajvPF8xuAACBAADIgqRPYEwu6AO2jc8GAQ" \
        -d chat_id=$chat_id
}
# Send info plox channel
function sendinfo() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$chat_id" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=html" \
        -d text="<b>New build available!</b>%0ADevice: <code>Xiaomi Redmi 4A (rolex)</code>%0ALinux version : <code>v3.18.140</code>%0ABranch : <code>$(git rev-parse --abbrev-ref HEAD)</code>%0ALast Commit: <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0AToolchain: <code>gcc version 4.9.x 20150123 (prerelease) (GCC)</code>%0AStart: <code>$(date)</code>%0ABuild Status: #Beta"
}
# Push kernel to channel
function push() {
    cd AnyKernel || exit 1
    ZIP=$(echo *.zip)
    curl -F document=@$ZIP "https://api.telegram.org/bot$token/sendDocument" \
        -F chat_id="$chat_id" \
        -F "disable_web_page_preview=true" \
        -F "parse_mode=html" \
        -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s)"
}
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$chat_id" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="Build throw an error(s)"
    exit 1
}
# Compile plox
function compile() {
    make -s -C "$(pwd)" -j"$(nproc)" O=out rolex_defconfig
    make -C "$(pwd)" CROSS_COMPILE="${GCC}" O=out -j"$(nproc)"
    if ! [ -a "$IMAGE" ]; then
        finerr
        exit 1
    fi
    cp out/arch/arm64/boot/Image.gz-dtb AnyKernel
}
# Zipping
function zipping() {
    cd AnyKernel || exit 1
    zip -r9 Elysium-rolex-${TANGGAL}.zip *
    cd .. #well
}
sticker
sendinfo
compile
zipping
END=$(date +"%s")
DIFF=$(($END - $START))
push
